[global]
    server string = internal-pages
    security = user
    map to guest = Never
    server min protocol = SMB2
    load printers = no
    printing = bsd
    printcap name = /dev/null
    disable spoolss = yes
    host msdfs = no
    wide links = no
    follow symlinks = no
    unix extensions = no
    acl allow execute always = yes
    mangled names = no
    dos charset = CP850
    unix charset = UTF-8

[site-a]
    path = /shares/site-a
    comment = site-a
    browseable = yes
    writable = yes
    read only = no
    guest ok = no
    valid users = site-a-writer
    force user = site-a-writer
    force group = site-a
    create mask = 0644
    directory mask = 0755

[site-b]
    path = /shares/site-b
    comment = site-b
    browseable = yes
    writable = yes
    read only = no
    guest ok = no
    valid users = site-b-writer
    force user = site-b-writer
    force group = site-b
    create mask = 0644
    directory mask = 0755
